# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit, pre-push]
minimum_pre_commit_version: "2.18"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # identify invalid files
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

      # git checks
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-case-conflict
      # - id: detect-aws-credentials

      # general quality checks
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: test
        name: test
        entry: ./scripts/validate_mkdocs.sh
        language: system
        pass_filenames: false
        always_run: true
        # verbose: true
        # require_serial: true
        stages: [pre-push]

ci:
  autoupdate_schedule: quarterly
