version: "3.9"
services:
  mkdocs:
    image: fyliu/mkdocs:testing-alpine3.18
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mkdocs
    command: mkdocs serve -a "0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
