site_name: Docker MkDocs

nav:
  - Home: index.md
  - User Guide: usage.md
  - Maintainer Guide: mkdocs.md
  - Guides ideas: guides-ideas.md
  - Tools:
    - DockerHub Guide: dockerhub.md
    - Git: git.md
    - Docker: docker.md
    - Poetry: poetry.md
  - License: license.md

theme:
  name: material
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.sections

repo_url: https://github.com/fyliu/docker-mkdocs
repo_name: fyliu/docker-mkdocs
edit_uri: edit/main/docs/

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.blocks.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      url_download: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      title: On this page
      permalink: true

watch:
  - README.md
  - LICENSE
